version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="test"
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'

  testing:
    container_name: jest
    image: node
    working_dir: /code
    volumes:
      - .:/code
    command: ["npm", "test", "--","lotterynumbers.service.spec.ts"]
